config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :looks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/look.rb
class Look < ApplicationRecord
  include LookPhotoUploader::Attachment.new(:photo)
  validates_presence_of :photo
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include AvatarUploader::Attachment.new(:avatar)
  include CoverPhotoUploader::Attachment.new(:cover_photo)

  validates_presence_of :avatar
  # validates_presence_of :cover_photo

  has_many :looks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
  def index
    @looks = Look.all.reverse
  end

  def show
    @look = Look.find(params[:id])
  end

  def new
    @look = Look.new
  end

  def edit
    @look = Look.find(params[:id])
  end

  def create
    @look = Look.new(look_params)
    if @look.save
      redirect_to @look
    else
      render 'new'
    end
  end

  def update
    @look = Look.find(params[:id])
    if @look.update(look_params)
      redirect_to @look
    else
      render 'edit'
    end
  end

  def destroy
    @look = Look.find(params[:id])
    @look.destroy
    redirect_to looks_path
  end

  private

  def look_params
    params.require(:look).permit(:user_id, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.reverse
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :cover_photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShrineSandbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/looks/_form.html.erb
<% if @look.errors.any? %>
  <div>
    <h2>
      <%= pluralize(@look.errors.count, "error") %> prohibited this look from being saved:
    </h2>
    <ul>
      <% @look.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @look, local: true do |form| %>
  <%= form.label :user_id %>
  <%= form.select :user_id, User.all.map(&:id) %>
  <br>
  <% if @look.photo %>
    <img src="<%= @look.photo_url(:large) %>">
    <br>
  <% end %>
  <%= form.label :photo %>
  <%= form.hidden_field :photo, value: @look.cached_photo_data %>
  <%= form.file_field :photo %>
  <br>
  <%= form.submit %>
<% end %>

app/views/looks/edit.html.erb
<h1>Edit look <%= @look.id %></h1>
<%= link_to 'Back', looks_path %>
<%= render 'looks/form' %>

app/views/looks/index.html.erb
<h1>Listing looks</h1>
<%= link_to "New look", new_look_path %>
<table>
  <tr>
    <th>Id</th>
    <th>User Id</th>
    <th>Photo</th>
    <th colspan="3"></th>
  </tr>

  <% @looks.each do |look| %>
    <tr>
      <td><%= look.id %></td>
      <td><%= link_to look.user_id, user_path(look.user) %></td>
      <td><img src="<%= look.photo_url(:small) %>"></td>
      <td><%= link_to "Show", look_path(look) %></td>
      <td><%= link_to "Edit", edit_look_path(look) %></td>
      <td><%= link_to "Destroy", look_path(look),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/looks/new.html.erb
<h1>New look</h1>
<%= link_to 'Back', looks_path %>
<%= render 'looks/form' %>

app/views/looks/show.html.erb
<h1>Show look <%= @look.id %></h1>
<%= link_to "Edit", edit_look_path(@look) %> |
<%= link_to 'Back', looks_path %>
<br>
<br>
User: <%= link_to @look.user_id, user_path(@look.user) %>
<br>
<%= link_to image_tag(@look.user.avatar_url(:small)), user_path(@look.user) %>
<br>
<br>
<img src="<%= @look.photo_url(:thumb) %>">
<img src="<%= @look.photo_url(:small) %>">
<img src="<%= @look.photo_url(:medium) %>">
<img src="<%= @look.photo_url(:large) %>">
<img src="<%= @look.photo_url(:list) %>">

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div>
    <h2>
      <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @user, local: true do |form| %>
  <% if @user.avatar %>
    <img src="<%= @user.avatar_url(:large) %>">
    <br>
  <% end %>
  <%= form.label :avatar %>
  <%= form.hidden_field :avatar, value: @user.cached_avatar_data %>
  <%= form.file_field :avatar %>
  <br>
  <% if @user.cover_photo %>
    <img src="<%= @user.cover_photo_url %>">
    <br>
  <% end %>
  <%= form.label :cover_photo %>
  <%= form.hidden_field :cover_photo, value: @user.cached_cover_photo_data %>
  <%= form.file_field :cover_photo %>
  <br>
  <%= form.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user <%= @user.id %></h1>
<%= link_to 'Back', users_path %>
<%= render 'users/form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<%= link_to "New user", new_user_path %>
<table>
  <tr>
    <th>Id</th>
    <th>Avatar</th>
    <th>Cover photo</th>
    <th colspan="3"></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><img src="<%= user.avatar_url(:large) %>"></td>
      <td><img src="<%= user.cover_photo_url %>"></td>
      <td><%= link_to "Show", user_path(user) %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Destroy", user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New user</h1>
<%= link_to 'Back', users_path %>
<%= render 'users/form' %>

app/views/users/show.html.erb
<h1>Show user <%= @user.id %></h1>
<%= link_to "Edit", edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<br>
<br>
<img src="<%= @user.cover_photo_url %>">
<br>
<br>
<img src="<%= @user.avatar_url(:large) %>">
<img src="<%= @user.avatar_url(:small) %>">
<br>
<br>

<div>
  <h2><%= pluralize(@user.looks.size, "look") %></h2>
  <% @user.looks.each do |look| %>
    <%= link_to image_tag(look.photo_url(:small)), look_path(look) %>
  <% end %>
</div>